export const SET_USER_INFO = "SET_USER_INFO";
export const SET_ERROR_REQUEST = "SET_ERROR_REQUEST";
export const SET_USER_REPOS = "SET_USER_REPOS";
export const SET_LOADING_USER_INFO = "SET_LOADING_USER_INFO";
export const SET_LOADING_USER_REPOS = "SET_LOADING_USER_REPOS";
export const SET_ERROR_USER_NOT_FOUND = "SET_ERROR_USER_NOT_FOUND";
